<img src="./airbnb.png" height="96" width="96">
<br />
<div style="text-align: center;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 5em;">Madrid Data Cleaning</span>
</div>

<br />
<div style="text-align: left;">
    <span style="color:#8585BB; font-family: 'Courier New'; font-size: 1.5em;">En las siguientes líneas de código estaremos haciendo una limpieza y exploración de los datos obtenidos de www.insideairbnb.com para la ciudad de Madrid.</span>
</div>

In [1]:
import sys
import pandas as pd                   
import datetime as dt                  
import numpy as np                    
import re

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print('Python version: ', sys.version)
print('Pandas version: ', pd.__version__)
print('Today: ', dt.date.today())

('Python version: ', '2.7.12 |Anaconda custom (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]')
('Pandas version: ', u'0.18.1')
('Today: ', datetime.date(2017, 7, 14))

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Vamos a echar un vistazo a nuestros datasets obtenidos de www.insideairbnb.com<br>
La data obtenida es del 08 de abril de 2017</span>
</div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Según Insideairbnb.com, la siguiente tabla es: *Detailed Listings data for Madrid*</span>
</div>

In [2]:
listing = pd.read_csv('./listings_1.csv', sep=',')
print 'Dimensión:', listing.shape
listing.tail(3)

Dimensión: (13335, 95)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
13332,16392617,https://www.airbnb.com/rooms/16392617,20170407214119,2017-04-08,"Piso con Terraza 2 personas, Aceptamos Mascotas","Piso acogedor, habitación individual para los ...",Hola! Somos dos hermanas jóvenes y compartimos...,"Piso acogedor, habitación individual para los ...",none,Está justo al lado del metro Jarama y autobuse...,NaN,NaN,Baño compartido recién reformado en color pist...,Pueden encontrarme en casa fuera de mi horario...,- Hora de entrada y salida Flexible previo avi...,https://a0.muscache.com/im/pictures/c9c35abc-f...,https://a0.muscache.com/im/pictures/c9c35abc-f...,https://a0.muscache.com/im/pictures/c9c35abc-f...,https://a0.muscache.com/im/pictures/c9c35abc-f...,17961354,https://www.airbnb.com/users/show/17961354,Laila,2014-07-11,"Madrid, Community of Madrid, Spain",NaN,within a day,50%,NaN,f,https://a0.muscache.com/im/users/17961354/prof...,https://a0.muscache.com/im/users/17961354/prof...,NaN,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"San Fernando de Henares, Comunidad de Madrid 2...",NaN,Casco Histórico de Vicálvaro,Vicálvaro,San Fernando de Henares,Comunidad de Madrid,28830,Madrid,"San Fernando de Henares, Spain",ES,Spain,40.422470,-3.526821,f,Apartment,Private room,2,1.0,1.0,2.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Pets...",NaN,$25.00,NaN,NaN,$100.00,$5.00,1,$0.00,1,1125,a week ago,NaN,26,56,86,361,2017-04-07,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN,NaN,f,flexible,f,f,1,NaN
13333,17840364,https://www.airbnb.com/rooms/17840364,20170407214119,2017-04-08,Apartamento pozuelo,Apartamento tranquilo muy cerca de Madrid ca...,NaN,Apartamento tranquilo muy cerca de Madrid ca...,none,NaN,NaN,NaN,NaN,NaN,El precio incluye limpieza De el apartamento,https://a0.muscache.com/im/pictures/1ec37eca-a...,https://a0.muscache.com/im/pictures/1ec37eca-a...,https://a0.muscache.com/im/pictures/1ec37eca-a...,https://a0.muscache.com/im/pictures/1ec37eca-a...,107332075,https://www.airbnb.com/users/show/107332075,Chely,2016-12-15,ES,NaN,within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/22e2e3b6-6...,https://a0.muscache.com/im/pictures/22e2e3b6-6...,Adelfas,3.0,3.0,"['email', 'phone', 'reviews']",t,f,"Pozuelo de Alarcón, Comunidad de Madrid 28224,...",NaN,El Plantío,Moncloa - Aravaca,Pozuelo de Alarcón,Comunidad de Madrid,28224,Madrid,"Pozuelo de Alarcón, Spain",ES,Spain,40.459903,-3.801603,f,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,""Wireless Internet"",Pool,Kitchen,...",NaN,$45.00,NaN,NaN,NaN,NaN,1,$15.00,2,1125,5 days ago,NaN,11,32,62,337,2017-04-08,1,2017-03-26,2017-03-26,100.0,10.0,10.0,10.0,10.0,8.0,10.0,t,NaN,NaN,f,flexible,f,f,3,1.0
13334,17829874,https://www.airbnb.com/rooms/17829874,20170407214119,2017-04-08,HABITACIÓN CON BAÑO PRIVADO,Habitación con baño privado. Zona verde y tran...,NaN,Habitación con baño privado. Zona verde y tran...,none,NaN,NaN,NaN,Habitación con baño . Zonas de acceso a la mis...,Poca conversación.,- No dar mucha conversación ni invadir espacio...,https://a0.muscache.com/im/pictures/884f1919-7...,https://a0.muscache.com/im/pictures/884f1919-7...,https://a0.muscache.com/im/pictures/884f1919-7...,https://a0.muscache.com/im/pictures/884f1919-7...,121929599,https://www.airbnb.com/users/show/121929599,Agm,2017-03-21,ES,NaN,within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/7fcc5040-c...,https://a0.muscache.com/im/pictures/7fcc5040-c...,NaN,1.0,1.0,"['email', 'phone']",t,f,"San Fernando de Henares, Comunidad de Madrid 2...",NaN,Casco Histórico de Vicálvaro,Vicálvaro,San Fernando de Henares,Comunidad de Madrid,28830,Madrid,"San Fernando de Henares, Spain",ES,Spain,40.422271,-3.531159,f,House,Private room,1,1.0,1.0,1.0,Real Bed,"{""Wireless Internet"",""Pets allowed"",Heating,Es...",NaN,$15.00,NaN,NaN,NaN,NaN,1,$0.00,1,90,4 days ago,NaN,15,45,75,350,2017-04-08,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN,NaN,f,strict,f,f,1,NaN

In [3]:
listing.columns

Index([u'id', u'listing_url', u'scrape_id', u'last_scraped', u'name',
       u'summary', u'space', u'description', u'experiences_offered',
       u'neighborhood_overview', u'notes', u'transit', u'access',
       u'interaction', u'house_rules', u'thumbnail_url', u'medium_url',
       u'picture_url', u'xl_picture_url', u'host_id', u'host_url',
       u'host_name', u'host_since', u'host_location', u'host_about',
       u'host_response_time', u'host_response_rate', u'host_acceptance_rate',
       u'host_is_superhost', u'host_thumbnail_url', u'host_picture_url',
       u'host_neighbourhood', u'host_listings_count',
       u'host_total_listings_count', u'host_verifications',
       u'host_has_profile_pic', u'host_identity_verified', u'street',
       u'neighbourhood', u'neighbourhood_cleansed',
       u'neighbourhood_group_cleansed', u'city', u'state', u'zipcode',
       u'market', u'smart_location', u'country_code', u'country', u'latitude',
       u'longitude', u'is_location_exact', u'property_type', u'room_type',
       u'accommodates', u'bathrooms', u'bedrooms', u'beds', u'bed_type',
       u'amenities', u'square_feet', u'price', u'weekly_price',
       u'monthly_price', u'security_deposit', u'cleaning_fee',
       u'guests_included', u'extra_people', u'minimum_nights',
       u'maximum_nights', u'calendar_updated', u'has_availability',
       u'availability_30', u'availability_60', u'availability_90',
       u'availability_365', u'calendar_last_scraped', u'number_of_reviews',
       u'first_review', u'last_review', u'review_scores_rating',
       u'review_scores_accuracy', u'review_scores_cleanliness',
       u'review_scores_checkin', u'review_scores_communication',
       u'review_scores_location', u'review_scores_value', u'requires_license',
       u'license', u'jurisdiction_names', u'instant_bookable',
       u'cancellation_policy', u'require_guest_profile_picture',
       u'require_guest_phone_verification', u'calculated_host_listings_count',
       u'reviews_per_month'],
      dtype='object')

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Según www.insideairbnb.com, la siguiente tabla es: *Summary information and metrics for listings in Madrid (good for visualisations)*.</span>
</div>

In [4]:
listing_sum = pd.read_csv('./listings.csv', sep=',')
print 'Dimensión:', listing_sum.shape
listing_sum.head(3)

Dimensión: (13335, 16)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,7830063,Quiet room in Plaza Mayor,41032693,Bluekitchen,Centro,Palacio,40.412275,-3.708718,Private room,42,2,100,2017-04-02,5.04,7,165
1,9898596,Homely apartment in the heart of Madrid,50908516,Daniel,Centro,Palacio,40.411093,-3.708985,Entire home/apt,135,1,68,2017-04-04,4.39,1,230
2,15334645,Piso Muy Luminoso en pleno centro de Madrid,97753616,Will,Centro,Palacio,40.413587,-3.708945,Entire home/apt,81,1,34,2017-03-21,5.57,1,287

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Según Insideairbnb.com, la siguiente tabla es: *Detailed Calendar Data for listings in Madrid*.</span>
</div>

In [5]:
calendar = pd.read_csv('./calendar.csv', sep=',')
calendar.tail(3)

         listing_id        date available   price
4867272    17829874  2017-04-10         t  $15.00
4867273    17829874  2017-04-09         t  $15.00
4867274    17829874  2017-04-08         f     NaN

In [6]:
#Según Insideairbnb.com, la siguiente tabla es: Detailed Review Data for listings in Madrid
review_sum = pd.read_csv('./reviews_1.csv')
review_sum.head(3)

   listing_id        date
0    15128601  2016-09-25
1    15128601  2016-10-03
2    15128601  2016-10-07

In [7]:
#Según Insideairbnb.com, la siguiente tabla es: Summary Review data and Listing ID (to facilitate time based analytics and visualisations linked to a listing).
review = pd.read_csv('./reviews.csv')
review.head(3)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,15128601,103956852,2016-09-25,48832799,Amparo,"Apartamento muy acogedor, limpio y cómodo, en ..."
1,15128601,105883025,2016-10-03,87158075,Daniela,"La descripción del anuncio era correcta, las f..."
2,15128601,106595943,2016-10-07,10102108,Fabien,Nice and cosy place. Really peaceful and quiet...

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Una vez vistos los datos que podemos obtener de Inside Airbnb, vamos a descartar las tablas resumidas y usar las tablas que tienen mayor cantidad de datos para poder moldearlas a nuestro gusto.<br><br></span>
</div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Las tablas que finalmente utilizaremos serán:<br><br>
- listing = pd.read_csv('./listings_1.csv', sep=',')<br>
- calendar = pd.read_csv('./calendar.csv', sep=',')<br>
- review = pd.read_csv('./reviews.csv')</span>
</div>

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">Data Cleaning</span>
</div>
<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Aunque los datos reales nunca están limpios completamente, necesitamos asegurarnos de limpiarlos lo mayor posible convirtiendo o eliminando valores nulos o faltantes.<br><br></span>
</div>

In [8]:
listing.describe().transpose()

C:\Users\ronny\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,count,mean,std,min,25%,50%,75%,max
id,13335.0,1.043929e+07,5.517349e+06,1.862800e+04,5.858327e+06,1.157754e+07,1.538489e+07,1.810984e+07
scrape_id,13335.0,2.017041e+13,4.890808e+00,2.017041e+13,2.017041e+13,2.017041e+13,2.017041e+13,2.017041e+13
host_id,13335.0,3.775842e+07,3.470057e+07,1.745300e+04,7.823688e+06,2.752699e+07,5.799251e+07,1.247534e+08
host_acceptance_rate,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_listings_count,13332.0,9.777453e+00,2.781298e+01,0.000000e+00,NaN,NaN,NaN,5.190000e+02
host_total_listings_count,13332.0,9.777453e+00,2.781298e+01,0.000000e+00,NaN,NaN,NaN,5.190000e+02
latitude,13335.0,4.042073e+01,2.034312e-02,4.033189e+01,4.041009e+01,4.041872e+01,4.042800e+01,4.056274e+01
longitude,13335.0,-3.697255e+00,2.383740e-02,-3.863907e+00,-3.707852e+00,-3.701596e+00,-3.693810e+00,-3.526821e+00
accommodates,13335.0,3.184252e+00,1.990534e+00,1.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,1.600000e+01
bathrooms,13285.0,1.251675e+00,5.981173e-01,0.000000e+00,NaN,NaN,NaN,8.000000e+00
bedrooms,13312.0,1.293495e+00,8.247503e-01,0.000000e+00,NaN,NaN,NaN,1.000000e+01
beds,13286.0,1.981936e+00,1.511608e+00,1.000000e+00,NaN,NaN,NaN,1.600000e+01
square_feet,522.0,3.758352e+02,5.459670e+02,0.000000e+00,NaN,NaN,NaN,5.167000e+03
guests_included,13335.0,1.572628e+00,1.088805e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.600000e+01
minimum_nights,13335.0,3.009824e+00,1.282894e+01,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,1.125000e+03
maximum_nights,13335.0,9.597532e+02,8.883119e+03,1.000000e+00,3.650000e+02,1.125000e+03,1.125000e+03,1.000000e+06
has_availability,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
availability_30,13335.0,8.831496e+00,9.152567e+00,0.000000e+00,0.000000e+00,6.000000e+00,1.400000e+01,3.000000e+01
availability_60,13335.0,2.307762e+01,1.958616e+01,0.000000e+00,5.000000e+00,2.000000e+01,3.800000e+01,6.000000e+01
availability_90,13335.0,4.030664e+01,2.942652e+01,0.000000e+00,1.300000e+01,3.800000e+01,6.500000e+01,9.000000e+01
availability_365,13335.0,2.058828e+02,1.269678e+02,0.000000e+00,8.400000e+01,2.470000e+02,3.210000e+02,3.650000e+02
number_of_reviews,13335.0,2.298755e+01,3.839320e+01,0.000000e+00,1.000000e+00,7.000000e+00,2.800000e+01,4.460000e+02
review_scores_rating,10417.0,9.162062e+01,8.983817e+00,2.000000e+01,NaN,NaN,NaN,1.000000e+02
review_scores_accuracy,10399.0,9.408020e+00,9.244271e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
review_scores_cleanliness,10405.0,9.326382e+00,9.949704e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
review_scores_checkin,10389.0,9.622293e+00,7.916267e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
review_scores_communication,10405.0,9.644786e+00,7.575793e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
review_scores_location,10387.0,9.542794e+00,7.666081e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
review_scores_value,10387.0,9.212573e+00,9.541097e-01,2.000000e+00,NaN,NaN,NaN,1.000000e+01
jurisdiction_names,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
calculated_host_listings_count,13335.0,7.600075e+00,1.961052e+01,1.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,1.450000e+02
reviews_per_month,10542.0,1.923220e+00,1.888180e+00,2.000000e-02,NaN,NaN,NaN,1.721000e+01

In [9]:
listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13335 entries, 0 to 13334
Data columns (total 95 columns):
id                                  13335 non-null int64
listing_url                         13335 non-null object
scrape_id                           13335 non-null int64
last_scraped                        13335 non-null object
name                                13335 non-null object
summary                             12846 non-null object
space                               9700 non-null object
description                         13329 non-null object
experiences_offered                 13335 non-null object
neighborhood_overview               8308 non-null object
notes                               5037 non-null object
transit                             8264 non-null object
access                              7546 non-null object
interaction                         7523 non-null object
house_rules                         8666 non-null object
thumbnail_url                       10847 non-null object
medium_url                          10847 non-null object
picture_url                         13335 non-null object
xl_picture_url                      10847 non-null object
host_id                             13335 non-null int64
host_url                            13335 non-null object
host_name                           13332 non-null object
host_since                          13332 non-null object
host_location                       13293 non-null object
host_about                          8282 non-null object
host_response_time                  11622 non-null object
host_response_rate                  11622 non-null object
host_acceptance_rate                0 non-null float64
host_is_superhost                   13332 non-null object
host_thumbnail_url                  13332 non-null object
host_picture_url                    13332 non-null object
host_neighbourhood                  9983 non-null object
host_listings_count                 13332 non-null float64
host_total_listings_count           13332 non-null float64
host_verifications                  13335 non-null object
host_has_profile_pic                13332 non-null object
host_identity_verified              13332 non-null object
street                              13335 non-null object
neighbourhood                       8772 non-null object
neighbourhood_cleansed              13335 non-null object
neighbourhood_group_cleansed        13335 non-null object
city                                13333 non-null object
state                               13292 non-null object
zipcode                             12896 non-null object
market                              13285 non-null object
smart_location                      13335 non-null object
country_code                        13335 non-null object
country                             13334 non-null object
latitude                            13335 non-null float64
longitude                           13335 non-null float64
is_location_exact                   13335 non-null object
property_type                       13335 non-null object
room_type                           13335 non-null object
accommodates                        13335 non-null int64
bathrooms                           13285 non-null float64
bedrooms                            13312 non-null float64
beds                                13286 non-null float64
bed_type                            13335 non-null object
amenities                           13335 non-null object
square_feet                         522 non-null float64
price                               13335 non-null object
weekly_price                        3512 non-null object
monthly_price                       3324 non-null object
security_deposit                    5731 non-null object
cleaning_fee                        7851 non-null object
guests_included                     13335 non-null int64
extra_people                        13335 non-null object
minimum_nights                      13335 non-null int64
maximum_nights                      13335 non-null int64
calendar_updated                    13335 non-null object
has_availability                    0 non-null float64
availability_30                     13335 non-null int64
availability_60                     13335 non-null int64
availability_90                     13335 non-null int64
availability_365                    13335 non-null int64
calendar_last_scraped               13335 non-null object
number_of_reviews                   13335 non-null int64
first_review                        10542 non-null object
last_review                         10541 non-null object
review_scores_rating                10417 non-null float64
review_scores_accuracy              10399 non-null float64
review_scores_cleanliness           10405 non-null float64
review_scores_checkin               10389 non-null float64
review_scores_communication         10405 non-null float64
review_scores_location              10387 non-null float64
review_scores_value                 10387 non-null float64
requires_license                    13335 non-null object
license                             249 non-null object
jurisdiction_names                  0 non-null float64
instant_bookable                    13335 non-null object
cancellation_policy                 13335 non-null object
require_guest_profile_picture       13335 non-null object
require_guest_phone_verification    13335 non-null object
calculated_host_listings_count      13335 non-null int64
reviews_per_month                   10542 non-null float64
dtypes: float64(19), int64(13), object(63)
memory usage: 9.7+ MB

In [10]:
#Existe alguna fila NULL?
print listing.isnull().any().any() 
print listing.shape

True
(13335, 95)

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Vamos a tratar de encontrar cuántos valores nulos existen en cada columna!</span>
</div>

In [11]:
listing.isnull().sum(axis=0)

id                                      0
listing_url                             0
scrape_id                               0
last_scraped                            0
name                                    0
summary                               489
space                                3635
description                             6
experiences_offered                     0
neighborhood_overview                5027
notes                                8298
transit                              5071
access                               5789
interaction                          5812
house_rules                          4669
thumbnail_url                        2488
medium_url                           2488
picture_url                             0
xl_picture_url                       2488
host_id                                 0
host_url                                0
host_name                               3
host_since                              3
host_location                          42
host_about                           5053
host_response_time                   1713
host_response_rate                   1713
host_acceptance_rate                13335
host_is_superhost                       3
host_thumbnail_url                      3
host_picture_url                        3
host_neighbourhood                   3352
host_listings_count                     3
host_total_listings_count               3
host_verifications                      0
host_has_profile_pic                    3
host_identity_verified                  3
street                                  0
neighbourhood                        4563
neighbourhood_cleansed                  0
neighbourhood_group_cleansed            0
city                                    2
state                                  43
zipcode                               439
market                                 50
smart_location                          0
country_code                            0
country                                 1
latitude                                0
longitude                               0
is_location_exact                       0
property_type                           0
room_type                               0
accommodates                            0
bathrooms                              50
bedrooms                               23
beds                                   49
bed_type                                0
amenities                               0
square_feet                         12813
price                                   0
weekly_price                         9823
monthly_price                       10011
security_deposit                     7604
cleaning_fee                         5484
guests_included                         0
extra_people                            0
minimum_nights                          0
maximum_nights                          0
calendar_updated                        0
has_availability                    13335
availability_30                         0
availability_60                         0
availability_90                         0
availability_365                        0
calendar_last_scraped                   0
number_of_reviews                       0
first_review                         2793
last_review                          2794
review_scores_rating                 2918
review_scores_accuracy               2936
review_scores_cleanliness            2930
review_scores_checkin                2946
review_scores_communication          2930
review_scores_location               2948
review_scores_value                  2948
requires_license                        0
license                             13086
jurisdiction_names                  13335
instant_bookable                        0
cancellation_policy                     0
require_guest_profile_picture           0
require_guest_phone_verification        0
calculated_host_listings_count          0
reviews_per_month                    2793
dtype: int64

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">El paso anterior ya nos dió un indicio de que hay varias columnas con datos únicamente nulos.</span>
</div>

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">Arreglando los Missing Values</span>
</div>
<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Primero vamos a borrar las columnas cuyos valores sean todos Nulos, ya que no aportan nada. Una de las posibles causas puede haber sido una mala captura de datos.<br><br></span>
</div>

In [12]:
listing.isnull().all()

id                                  False
listing_url                         False
scrape_id                           False
last_scraped                        False
name                                False
summary                             False
space                               False
description                         False
experiences_offered                 False
neighborhood_overview               False
notes                               False
transit                             False
access                              False
interaction                         False
house_rules                         False
thumbnail_url                       False
medium_url                          False
picture_url                         False
xl_picture_url                      False
host_id                             False
host_url                            False
host_name                           False
host_since                          False
host_location                       False
host_about                          False
host_response_time                  False
host_response_rate                  False
host_acceptance_rate                 True
host_is_superhost                   False
host_thumbnail_url                  False
host_picture_url                    False
host_neighbourhood                  False
host_listings_count                 False
host_total_listings_count           False
host_verifications                  False
host_has_profile_pic                False
host_identity_verified              False
street                              False
neighbourhood                       False
neighbourhood_cleansed              False
neighbourhood_group_cleansed        False
city                                False
state                               False
zipcode                             False
market                              False
smart_location                      False
country_code                        False
country                             False
latitude                            False
longitude                           False
is_location_exact                   False
property_type                       False
room_type                           False
accommodates                        False
bathrooms                           False
bedrooms                            False
beds                                False
bed_type                            False
amenities                           False
square_feet                         False
price                               False
weekly_price                        False
monthly_price                       False
security_deposit                    False
cleaning_fee                        False
guests_included                     False
extra_people                        False
minimum_nights                      False
maximum_nights                      False
calendar_updated                    False
has_availability                     True
availability_30                     False
availability_60                     False
availability_90                     False
availability_365                    False
calendar_last_scraped               False
number_of_reviews                   False
first_review                        False
last_review                         False
review_scores_rating                False
review_scores_accuracy              False
review_scores_cleanliness           False
review_scores_checkin               False
review_scores_communication         False
review_scores_location              False
review_scores_value                 False
requires_license                    False
license                             False
jurisdiction_names                   True
instant_bookable                    False
cancellation_policy                 False
require_guest_profile_picture       False
require_guest_phone_verification    False
calculated_host_listings_count      False
reviews_per_month                   False
dtype: bool

In [13]:
print listing['jurisdiction_names'].unique()
print listing['has_availability'].unique()
print listing['host_acceptance_rate'].unique()

[ nan]
[ nan]
[ nan]

In [14]:
listing.drop('jurisdiction_names', axis=1, inplace=True)
listing.drop('has_availability', axis=1, inplace=True)
listing.drop('host_acceptance_rate', axis=1, inplace=True)

In [15]:
listing.shape

(13335, 92)

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">Sampling</span>
</div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Nuestra tabla de datos tiene muchas líneas o registros. Para no afectar el funcionamiento de nuestro ordenador, cuando queramos revisar los tipos de datos sólo miraremos pocas líneas a la vez. Ahora bien, en vez de mirar las mismas 2, 5 ó 10 líneas principales cada vez, aplicaremos lo siguiente con lo que conseguiremos ver una muestra aleatoria diferente en nuestro head(). De esta manera, nos aseguramos de que los datos no estén en ningún orden particular cuando probamos el muestreo (como tomar filas de arriba o de abajo) al mezclar aleatoriamente las filas.<br><br></span>
</div>

In [16]:
#Shuffle de las filas de "listing" para que obtengamos una muestra distribuida cuando mostramos el head()

listing = listing.reindex(np.random.permutation(listing.index))
listing.head(3)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
8965,18095441,https://www.airbnb.com/rooms/18095441,20170407214119,2017-04-08,Habitación con cama de matrimonio Barrio Salam...,Habitación privada con cama de matrimonio. Der...,"La ubicación, limpieza y comodidad",Habitación privada con cama de matrimonio. Der...,none,Bueno,"Recomendado para viajes de negocios, placer ó ...","Entrada del Metro de O'Donell, Goya y Manuel B...",Cocina-comedor y baño a compartir con propietaria,Sólo se coincidirá puntuslmente a lo largo del...,"Respetar las horas de silencio en la noche, y ...",https://a0.muscache.com/im/pictures/e848ba24-d...,https://a0.muscache.com/im/pictures/e848ba24-d...,https://a0.muscache.com/im/pictures/e848ba24-d...,https://a0.muscache.com/im/pictures/e848ba24-d...,124597861,https://www.airbnb.com/users/show/124597861,Esther,2017-04-06,"Madrid, Community of Madrid, Spain",NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/7f61af8f-6...,https://a0.muscache.com/im/pictures/7f61af8f-6...,NaN,1.0,1.0,"['email', 'phone', 'facebook']",t,f,"Madrid, Comunidad de Madrid, Spain",NaN,Prosperidad,Chamartín,Madrid,Comunidad de Madrid,NaN,Madrid,"Madrid, Spain",ES,Spain,40.440998,-3.678284,f,House,Private room,2,1.0,1.0,1.0,Real Bed,"{""Cable TV"",""Wireless Internet"",Kitchen,""Smoki...",NaN,$50.00,NaN,NaN,NaN,NaN,1,$0.00,1,7,today,22,52,82,357,2017-04-07,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN,f,moderate,f,f,1,NaN
5575,7745816,https://www.airbnb.com/rooms/7745816,20170407214119,2017-04-08,Precioso apto. al lado de Gran Vía,Apartamento muy acogedor completamente reforma...,"El apartamento consta de dos espacios, como se...",Apartamento muy acogedor completamente reforma...,none,Localización inmejorable. El barrio es el míti...,NaN,"Hay varios metros al lado de casa: Noviciado, ...",Al ser una vivienda de uso propio que se ofrec...,Dispondréis de mi teléfono por si tuvierais cu...,El apartamento se entrega limpio y en perfecto...,NaN,NaN,https://a0.muscache.com/im/pictures/98576927/7...,NaN,19227342,https://www.airbnb.com/users/show/19227342,Gabriel,2014-07-31,"Madrid, Community of Madrid, Spain",NaN,within a day,100%,f,https://a0.muscache.com/im/users/19227342/prof...,https://a0.muscache.com/im/users/19227342/prof...,Malasaña,1.0,1.0,"['email', 'phone', 'reviews']",t,f,"Malasaña, Madrid, Comunidad de Madrid 28004, S...",Malasaña,Universidad,Centro,Madrid,Comunidad de Madrid,28004,Madrid,"Madrid, Spain",ES,Spain,40.425760,-3.707467,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",NaN,$52.00,NaN,NaN,$500.00,NaN,2,$25.00,2,1125,2 months ago,0,0,0,0,2017-04-08,5,2016-05-30,2016-11-13,92.0,10.0,10.0,10.0,10.0,9.0,9.0,t,NaN,f,strict,f,f,1,0.48
11498,7469234,https://www.airbnb.com/rooms/7469234,20170407214119,2017-04-08,"MADRID RIO room, luminous, metro station",MADRID RIO. Beautiful and bright room. 20 mete...,"Magnifient apartment, great common areas",MADRID RIO. Beautiful and bright room. 20 mete...,none,5 minutes walking from Madrid Rio y and Princi...,Car parking 12€/day,The closest metro station is less than 20 mete...,Living room/dining room. Internet WiFi 20Mb.,The keys are delivered in person. Facilities a...,Enjoy the apartment and respec it. Respect to ...,NaN,NaN,https://a0.muscache.com/im/pictures/94700232/4...,NaN,24085430,https://www.airbnb.com/users/show/24085430,Lorenzo,2014-11-23,"Madrid, Community of Madrid, Spain","Madrid, me gusta pasear, ir en bici, beber/com...",within a day,86%,f,https://a0.muscache.com/im/users/24085430/prof...,https://a0.muscache.com/im/users/24085430/prof...,Argüelles,11.0,11.0,"['email', 'phone', 'reviews', 'jumio', 'work_e...",t,t,"Aluche, Madrid, Comunidad de Madrid, Spain",Aluche,Puerta del Angel,Latina,Madrid,Comunidad de Madrid,NaN,Madrid,"Madrid, Spain",ES,Spain,40.414894,-3.724432,f,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",NaN,$39.00,$290.00,$802.00,NaN,$10.00,1,$0.00,30,365,7 weeks ago,0,1,7,97,2017-04-08,2,2015-09-05,2016-11-08,90.0,9.0,8.0,10.0,9.0,10.0,10.0,t,NaN,f,flexible,f,f,10,0.10

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Existen otras columnas con datos que no nos interesan, por ellos procederemos a eliminarlas:
<br></span>
</div>

In [17]:
delete = ['listing_url', 'scrape_id', 'last_scraped', 'thumbnail_url', 'medium_url','country_code','calendar_last_scraped', 
          'is_location_exact', 'host_neighbourhood', 'picture_url', 'xl_picture_url', 'host_thumbnail_url', 'host_picture_url', 
          'summary', 'description','host_url', 'experiences_offered', 'space', 'neighborhood_overview', 'notes', 'transit', 
          'access', 'interaction', 'house_rules', 'host_about', 'host_response_time', 'host_response_rate', 'square_feet', 
          'license']   
len(delete)

29

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">El dato de "square_feet" lo borramos porque contiene muchos datos nulos, aunque podría ser un dato interesante para -por ejemplo- determinar el precio de alquiler del piso; aunque en el caso de AirBnB (si vamos a la concepción inicial de la idea de la compañia: compartir sofá) también podría considerarse como un dato menor. 
<br></span>
</div>

In [18]:
for i in range(0,len(delete)):
    listing.drop(delete[i], axis=1, inplace=True)

In [19]:
listing.shape

(13335, 63)

In [20]:
listing = listing.reindex(np.random.permutation(listing.index))
listing.head(3)

,id,name,host_id,host_name,host_since,host_location,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
9135,1690312,Apartamento 200m2 para 5/6 personas,8815003,Maite,2013-09-13,"Madrid, Community of Madrid, Spain",f,2.0,2.0,"['email', 'phone', 'reviews', 'jumio']",t,t,"Madrid, Community of Madrid 28016, Spain",NaN,Hispanoamérica,Chamartín,Madrid,Community of Madrid,28016,Madrid,"Madrid, Spain",Spain,40.456181,-3.676956,Apartment,Entire home/apt,6,2.0,3.0,3.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$200.00,NaN,NaN,$500.00,NaN,1,$50.00,2,7,2 weeks ago,30,60,90,365,1,2015-05-24,2015-05-24,80.0,8.0,10.0,10.0,8.0,10.0,8.0,t,f,flexible,f,f,2,0.04
441,4678105,Central sunny apartment with views,17705919,Barbara Y Javi,2014-07-06,"Madrid, Community of Madrid, Spain",f,1.0,1.0,"['email', 'phone', 'reviews', 'jumio']",t,t,"Madrid, Comunidad de Madrid 28005, Spain",NaN,Palacio,Centro,Madrid,Comunidad de Madrid,28005,Madrid,"Madrid, Spain",Spain,40.412441,-3.711110,Apartment,Entire home/apt,2,1.0,2.0,2.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Elev...",$100.00,NaN,NaN,$150.00,$10.00,1,$0.00,2,1125,2 weeks ago,0,6,36,311,20,2015-02-01,2016-10-04,94.0,9.0,9.0,10.0,10.0,10.0,9.0,t,f,flexible,f,f,1,0.75
5021,13091807,long rental study old town madrid 2,21137168,Ale,2014-09-09,Spain,f,4.0,4.0,"['email', 'phone', 'reviews']",t,f,"Malasaña, Madrid, Comunidad de Madrid 28004, S...",Malasaña,Universidad,Centro,Madrid,Comunidad de Madrid,28004,Madrid,"Madrid, Spain",Spain,40.426694,-3.707727,Apartment,Private room,2,1.0,2.0,1.0,Real Bed,"{Internet,""Wireless Internet"",""Air conditionin...",$39.00,NaN,NaN,NaN,NaN,1,$0.00,7,365,today,7,9,29,281,2,2017-03-07,2017-03-20,80.0,10.0,9.0,10.0,9.0,10.0,10.0,t,t,strict,f,f,4,1.82

In [21]:
listing.price.head()

9135     $200.00
441      $100.00
5021      $39.00
12574    $120.00
2928      $60.00
Name: price, dtype: object

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Debo eliminar el simbolo de dolar en la columna de precio y convertirlo en un dato tipo float.<br></span>
</div>

In [22]:
def transform_price(df, variables=None):
    df = df.copy()
    for variable in variables:
        df[variable] = df[variable].str.strip('$').str.replace(',', '') \
            # Remove dollar signs and thousands separators
        df[variable] = df[variable].astype(np.float64)
    return df


vars_price = ['cleaning_fee', 'price', 'extra_people', 'weekly_price', 'monthly_price' ]
listing = transform_price(listing, vars_price)

In [23]:
listing['price'].head(5)

9135     200.0
441      100.0
5021      39.0
12574    120.0
2928      60.0
Name: price, dtype: float64

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">También se podría hacer de la siguiente manera:<br><br></span></div>
    
<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.2em;"> listing['price']=listing['price'].str.strip('$').str.replace(',', '') <br>
listing['price'] = pd.to_numeric(listing.price)</span></div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">O tambien, quitamos el símbolo de $ y el separador de miles en los valores no nulos "NA":
<br><br></span></div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.2em;">listing['price'] = listing.loc[listing.price.notnull()].price.apply(lambda x: re.sub('$', '', x))<br>
listing['price'] = pd.to_numeric(listing.price)
<br></span></div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Seguimos limpiando datos...<br></span>
</div>

In [24]:
variables = ['state', 'city', 'market', 'smart_location', 'country', 'neighbourhood', 'neighbourhood_cleansed',
             'neighbourhood_group_cleansed', 'host_location', 'street']

for i in range(0,len(variables)-1):
    print variables[i]
    print listing[variables[i]].unique()
    print ''

state
['Community of Madrid' 'Comunidad de Madrid' nan 'Madrid'
 '\xe9\xa6\xac\xe5\xbe\xb7\xe9\x87\x8c\xe8\x87\xaa\xe6\xb2\xbb\xe5\x8d\x80'
 'madrid'
 '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c\xe8\x87\xaa\xe6\xb2\xbb\xe5\x8c\xba'
 'Communaut\xc3\xa9 de Madrid' 'Madrid \nMadrid' 'Salerno Fisciano' 'Spain'
 'Madrid, Spain' 'Espa\xc3\xb1a' 'Autonome Gemeinschaft Madrid'
 '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c' '28' 'Usera' 'Valencian Community'
 'MADRID' 'Madrid Espa\xc3\xb1a' ' ' 'Alicante' '  ' 'Espa\xc5\x84a'
 'Madrid capital' 'La Habana' 'Barcelona'
 '\xe8\xa5\xbf\xe7\x8f\xad\xe7\x89\x99' 'Espa\xc3\xb1a,Madrid'
 'Regi\xc3\xa3o Aut\xc3\xb4noma de Madrid']

city
['Madrid' '\xe9\xa6\xac\xe5\xbe\xb7\xe9\x87\x8c'
 'Madrid, Comunidad de Madrid, ES' '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c'
 'Madrid ' 'Valderrodrigo' ' Madrid' 'Salerno' 'Pozuelo de Alarc\xc3\xb3n'
 'San L\xc3\xa1zaro' 'M\xc3\xa1laga' 'Boadilla del Monte' 'Pozuelo'
 'madrid' 'MADRID' 'MADRID ' 'Chueca, Madrid' nan 'villa verde bajo'
 'Madrid, Comunidad de Madrid, ESPANA' 'San Fernando de Henares' 'Chiva'
 'Centro, Madrid' 'Aravaca ' ' ' 'Onil' 'las matas  madrid' '  '
 'Madrid, Vallecas (Fontarr\xc3\xb3n)' 'Centro' 'Madid' 'La Habana'
 'Chueca' 'La Elipa' 'Aravaca (Madrid)' 'Motilla del Palancar' '\nDelicias'
 'Delicias-Madrid' 'Barcelona ' 'Ventas' 'Malaga' 'Madri'
 'Comunidad de Madrid']

market
['Madrid' nan 'London' 'Deauville' 'Other (International)' 'Toledo']

smart_location
['Madrid, Spain' '\xe9\xa6\xac\xe5\xbe\xb7\xe9\x87\x8c, Spain'
 'Madrid, Comunidad de Madrid, ES, Spain'
 '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c, Spain' 'Madrid , Spain'
 'Valderrodrigo, Spain' ' Madrid, Spain' 'Salerno'
 'Pozuelo de Alarc\xc3\xb3n, Spain' 'San L\xc3\xa1zaro, Spain'
 'M\xc3\xa1laga, Spain' 'Boadilla del Monte, Spain' 'Pozuelo, Spain'
 'madrid, Spain' 'MADRID, Spain' 'MADRID , Spain' 'Chueca, Madrid, Spain'
 'villa verde bajo, Spain' 'Madrid, Comunidad de Madrid, ESPANA, Spain'
 'San Fernando de Henares, Spain' 'Chiva, Spain' 'Centro, Madrid, Spain'
 'Aravaca , Spain' 'ES, Spain' 'Onil, Spain' 'las matas  madrid, Spain'
 'Madrid, Vallecas (Fontarr\xc3\xb3n), Spain' 'Centro, Spain'
 'Madid, Spain' 'La Habana, Cuba' 'Chueca, Spain' 'La Elipa, Spain'
 'Aravaca (Madrid), Spain' 'Motilla del Palancar, Spain'
 '\nDelicias, Spain' 'Delicias-Madrid, Spain' 'Barcelona , Spain'
 'Ventas, Spain' 'Malaga, Spain' 'Madri, Spain'
 'Comunidad de Madrid, Spain']

country
['Spain' nan 'Cuba']

neighbourhood
[nan 'Malasa\xc3\xb1a' 'Embajadores' 'Aluche' 'Delicias' 'Justicia'
 'Ciudad Jardin' 'Cortes' 'Arg\xc3\xbcelles' 'Guindalera' 'Ciudad Lineal'
 'Palos do Moguer' 'Cuatro Caminos' 'Arapiles' 'Carabanchel' 'Gaztambide'
 'Sol' 'Hortaleza' 'Castilla' 'Adelfas' 'Pacifico' 'La Latina'
 'Bellas Vistas' 'San Blas' 'Recoletos' 'Almagro' 'Acacias' 'Valdeacederas'
 'Ibiza' 'Trafalgar' 'Fuente del Berro' 'Goya' 'El Tr\xc3\xa9ntaiseis'
 'Prosperidad' 'Almenara' 'Hispanoam\xc3\xa9rica' 'Castillejos' 'Palacio'
 'La Chopera' 'Legazpi' 'Moncloa' 'Castellana' 'Centro'
 'Puente de Vallecas' 'Usera' 'Nueva Espa\xc3\xb1a' 'Imperial' 'Barajas'
 'Lista' 'Moratalaz' 'Villaverde' 'Rios Rosas' 'Fuencarral-el Pardo'
 'Berruguete' 'Jer\xc3\xb3nimos' 'El Viso' 'Chamber\xc3\xad' 'Retiro'
 'Vallehermosa' 'Estrella' 'Vic\xc3\xa1lvaro' 'Tetu\xc3\xa1n'
 'Villa de Vallecas' 'Fuencarral-El Pardo' 'Arganzuela' 'Atocha']

neighbourhood_cleansed
['Hispanoam\xc3\xa9rica' 'Palacio' 'Universidad' 'Pueblo Nuevo'
 'Embajadores' 'Puerta del Angel' 'Delicias' 'Arapiles' 'Justicia'
 'Ciudad Jard\xc3\xadn' 'Fuente del Berro' 'Cortes' 'Arg\xc3\xbcelles'
 'Guindalera' 'Costillares' 'Comillas' 'Palos de Moguer' 'Cuatro Caminos'
 'Buenavista' 'Gaztambide' 'Sol' 'Acacias' 'Palomas' 'Lista' 'Castilla'
 'Puerta Bonita' 'Vallehermoso' 'Adelfas' 'La Paz' 'Trafalgar'
 'Vista Alegre' 'Pac\xc3\xadfico' 'Numancia' 'Bellas Vistas' 'Salvador'
 'Recoletos' 'Almagro' 'Pradolongo' 'Ibiza' 'Imperial' 'Valdeacederas'
 'Amposta' 'San Pascual' 'Castellana' 'Goya' 'Ni\xc3\xb1o Jes\xc3\xbas'
 'Prosperidad' 'Almenara' 'Berruguete' 'Valdefuentes' 'Jer\xc3\xb3nimos'
 'Castillejos' 'Colina' 'Los Rosales' 'Chopera' 'El Viso' 'Legazpi'
 'Quintana' 'Casco Hist\xc3\xb3rico de Vic\xc3\xa1lvaro'
 'Ciudad Universitaria' 'Simancas' 'San Isidro' 'Pinar del Rey' 'Canillas'
 'Opa\xc3\xb1el' 'Los Angeles' 'Ventas' 'Palomeras Bajas' 'Zof\xc3\xado'
 'Canillejas' 'Aluche' 'Nueva Espa\xc3\xb1a' 'Pilar' 'San Diego'
 'San Ferm\xc3\xadn' 'Rios Rosas' 'Alameda de Osuna' 'Vinateros'
 'San Juan Bautista' 'Valverde' 'Rosas' 'San Andr\xc3\xa9s' 'Casa de Campo'
 'Pe\xc3\xb1agrande' 'Concepci\xc3\xb3n' 'Aravaca' 'Hell\xc3\xadn'
 'Abrantes' 'Casco Hist\xc3\xb3rico de Vallecas' 'Atocha' 'Almendrales'
 'Lucero' 'Piovera' 'Valdezarza' 'Entrev\xc3\xadas' 'Fontarr\xc3\xb3n'
 'Casco Hist\xc3\xb3rico de Barajas' 'Moscard\xc3\xb3' 'Arcos' 'Portazgo'
 'C\xc3\xa1rmenes' 'Apostol Santiago' 'Media Legua' 'San Cristobal'
 'Valdemar\xc3\xadn' 'Aeropuerto' 'Marroquina' 'Mirasierra'
 'Palomeras Sureste' 'Rejas' 'Pavones' 'Aguilas' 'Estrella' 'Ambroz'
 'Corralejos' 'Tim\xc3\xb3n' 'Campamento' 'Orcasur' 'Butarque' 'El Goloso'
 'Fuentelareina' 'Santa Eugenia' 'Cuatro Vientos' 'Orcasitas'
 'El Plant\xc3\xado' 'El Pardo']

neighbourhood_group_cleansed
['Chamart\xc3\xadn' 'Centro' 'Ciudad Lineal' 'Latina' 'Arganzuela'
 'Chamber\xc3\xad' 'Salamanca' 'Moncloa - Aravaca' 'Carabanchel'
 'Tetu\xc3\xa1n' 'Hortaleza' 'Retiro' 'Fuencarral - El Pardo'
 'Puente de Vallecas' 'San Blas - Canillejas' 'Usera' 'Villaverde'
 'Vic\xc3\xa1lvaro' 'Barajas' 'Moratalaz' 'Villa de Vallecas']

host_location
['Madrid, Community of Madrid, Spain' 'Spain ' 'ES' 'Madrid, Madrid, Spain'
 'US' 'Torremolinos, Andaluc\xc3\xada, Spain'
 'Alexandria, Virginia, United States' 'Marbella, Andaluc\xc3\xada, Spain'
 'Taipei City, Taiwan' 'Spain' 'Majadahonda, Madrid, Spain'
 'Pozuelo de Alarc\xc3\xb3n, Comunidad de Madrid, Spain' 'Espa\xc3\xb1a'
 'Bogajo, Castilla y Le\xc3\xb3n, Spain'
 'Villanueva del Pardillo, Comunidad de Madrid, Spain'
 'Eureka, California, United States'
 'Vitoria-Gasteiz, Basque Country, Spain'
 'Majadahonda, Comunidad de Madrid, Spain'
 'Sevilla, Andaluc\xc3\xada, Spain'
 'Alcala de Henares, Community of Madrid, Spain' 'London'
 'Aranjuez, Community of Madrid, Spain' 'Capital District, Venezuela'
 'Beirut, Beirut, Lebanon' 'CA' 'Torrelodones, Comunidad de Madrid, Spain'
 'Toulouse, Midi-Pyr\xc3\xa9n\xc3\xa9es, France'
 'Paris, \xc3\x8ele-de-France, France' 'Barcelona, Catalu\xc3\xb1a, Spain'
 'Bethesda, Maryland, United States'
 'Viso del Marqu\xc3\xa9s, Castilla-La Mancha, Spain'
 'Salerno, Campania, Italy' 'Colombia/ Espa\xc3\xb1a/ Italia'
 'Parla, Community of Madrid, Spain' 'New York, New York, United States'
 'London, England, United Kingdom' 'Burgos, Castilla y Le\xc3\xb3n, Spain'
 'Luxembourg' 'Barcelona, Catalonia, Spain' 'France'
 'Dubai, Dubai, United Arab Emirates' 'Community of Madrid, Spain'
 'Valencia, Valencian Community, Spain'
 'Legan\xc3\xa9s, Community of Madrid, Spain' 'CN'
 'Seville, Andalusia, Spain'
 'Paracuellos de Jarama, Comunidad de Madrid, Spain'
 'Las Palmas de Gran Canaria, Canary Islands, Spain' 'Andalusia, Spain'
 'Segovia, Castile and Le\xc3\xb3n, Spain'
 'Casco Hist\xc3\xb3rico De Calarc\xc3\xa1, Quindio, Colombia'
 'Irun, Basque Country, Spain' 'A Coru\xc3\xb1a, Galicia, Spain'
 'Le Mesnil-Esnard, Normandy, France'
 'San Sebasti\xc3\xa1n, Basque Country, Spain'
 'Getafe, Comunidad de Madrid, Spain' 'Cabra, Andalusia, Spain'
 'La Mesa, California, United States'
 'Le Chesnay, \xc3\x8ele-de-France, France'
 'Logro\xc3\xb1o, La Rioja, Spain' 'Fuengirola, Andaluc\xc3\xada, Spain'
 'Navalcarnero, Community of Madrid, Spain' 'Fitzroy, Victoria, Australia'
 'Bogota, Bogota, Colombia' 'Perugia, Umbria, Italy'
 'Ajaccio, Corsica, France' 'Brussels, Brussels, Belgium'
 'Albox, Andaluc\xc3\xada, Spain' 'Las Rozas, Community of Madrid, Spain'
 'Edinburgh, Scotland, United Kingdom' nan 'Lima, Lima, Peru'
 'Basel, Basel-Stadt, Switzerland' 'Mallorca, Spain' 'PA'
 'Alpedrete, Madrid, Spain' 'Warsaw, Masovian Voivodeship, Poland'
 'Santa Cruz de la Palma, Canary Islands, Spain' 'Espana' 'Buenos Aires'
 'FR' 'Salamanca, Castilla y Le\xc3\xb3n, Spain'
 'Palma, Balearic Islands, Spain'
 'Argentina, Castilla y Le\xc3\xb3n, Spain' 'Naples, Campania, Italy'
 'Galapagar, Comunidad de Madrid, Spain' 'Corella, Navarre, Spain'
 'Ciempozuelos, Comunidad de Madrid, Spain'
 'Arroyomolinos, Community of Madrid, Spain'
 'Velilla de San Antonio, Community of Madrid, Spain' 'IT'
 'Granada, Andalusia, Spain' 'C\xc3\xb3rdoba, Andalusia, Spain'
 'Arrecife, Canary Islands, Spain'
 'Santa Cruz de Tenerife, Canary Islands, Spain'
 'Rez\xc3\xa9, Pays de la Loire, France'
 'Benalm\xc3\xa1dena, Andaluc\xc3\xada, Spain' 'Berlin, Berlin, Germany'
 'Salamanca, Castile and Le\xc3\xb3n, Spain' 'Chueca,Madrid'
 'Fort Pierce, Florida, United States'
 'Amsterdam, North Holland, Netherlands' 'Ibiza, Balearic Islands, Spain'
 'El Escorial, Community of Madrid, Spain'
 'El Escorial, Comunidad de Madrid, Spain'
 'Alcobendas, Comunidad de Madrid, Spain' 'Canicatt\xc3\xac, Sicily, Italy'
 'Deutschland' 'Seattle, Washington, United States'
 'Alcobendas, Community of Madrid, Spain'
 'en Madrid cerca de El Escorial, localidad hist\xc3\xb3rica'
 'Pozuelo de Alarc\xc3\xb3n, Community of Madrid, Spain'
 'Seoul, South Korea' 'Bail\xc3\xa9n, Andalusia, Spain'
 'Bilbao, Basque Country, Spain' 'Zaragoza, Aragon, Spain'
 'Guadalajara, Castilla-La Mancha, Spain'
 'Guadalajara, Castile-La Mancha, Spain' 'Mechelen, Flanders, Belgium'
 'Santa Cruz de la Zarza, Castilla-La Mancha, Spain' 'NL'
 'Lleida, Catalonia, Spain' 'Tres Cantos, Community of Madrid, Spain'
 'San Antonio, Valparaiso, Chile' 'Madrid, New York, United States'
 'Region of Murcia, Spain' 'City of Brussels, Brussels, Belgium'
 'Espa\xc3\xb1a ' 'Calamonte, Extremadura, Spain'
 'Toronto, Ontario, Canada' 'Calle Mirasierra 16 bajo izquierda'
 'Caracas, Capital District, Venezuela'
 'Moraira, Comunidad Valenciana, Spain' 'United States'
 'Vivo en Madrid, en el mismo piso que ofrezco, pero es muy grande, quiz\xc3\xa1 nos divisemos en el sal\xc3\xb3n.'
 'Hong Kong' 'San Mart\xc3\xadn de la Vega, Comunidad de Madrid, Spain'
 'Azuqueca de Henares, Castile-La Mancha, Spain'
 'Doctor Tolosa Latour 19 escalera 2   1-A' 'Hilo, Hawaii, United States'
 'Daganzo de Arriba, Comunidad de Madrid, Spain'
 'Santiago de Compostela, Galicia, Spain' 'Geneva, Geneva, Switzerland'
 'Tomelloso, Castilla-La Mancha, Spain' 'Pinto, Community of Madrid, Spain'
 'Altea, Valencian Community, Spain' 'Madrid, Caraga, Philippines'
 'En el mismo  piso' 'Munich, Bavaria, Germany'
 'Berkeley, California, United States'
 'Alicante, Valencian Community, Spain'
 'Quintanar de la Orden, Castile-La Mancha, Spain'
 'M\xc3\xa1laga, Andalusia, Spain' 'Albacete, Castile-La Mancha, Spain'
 'Palma de Mallorca, Balearic Islands, Spain'
 'Montreal, Qu\xc3\xa9bec, Canada' 'Bordeaux, Aquitaine, France'
 'Mahon, Balearic Islands, Spain'
 'Las Pedro\xc3\xb1eras, Castilla-La Mancha, Spain' 'Rome, Lazio, Italy'
 'Venice, Veneto, Italy' 'Sydney, New South Wales, Australia'
 'Lake Forest, California, United States' 'X\xc3\xa0tiva, Valencia, Spain'
 'Grenoble, Auvergne-Rh\xc3\xb4ne-Alpes, France'
 'Fuentes, Castilla-La Mancha, Spain'
 'Amsterdam, Noord-Holland, The Netherlands'
 'Alcorc\xc3\xb3n, Comunidad de Madrid, Spain'
 'Ramos Mej\xc3\xada, Buenos Aires Province, Argentina'
 'Ontinyent, Valencian Community, Spain'
 'Albacete, Castilla-La Mancha, Spain' 'United Kingdom' 'AU'
 'Majadahonda, Community of Madrid, Spain' 'Spain\n' 'Kfar Saba, Israel'
 'Villanueva de San Mancio, Castilla y Le\xc3\xb3n, Spain'
 'eloy gonzalo 19, 2\xc2\xbab' 'Chicago, Illinois, United States'
 'D\xc3\xbcsseldorf, North Rhine-Westphalia, Germany'
 'Almer\xc3\xada, Andalusia, Spain' 'London, UK'
 'M\xc3\xb3stoles, Community of Madrid, Spain' ' Spain'
 'Montevideo, Montevideo Department, Uruguay'
 '\xc3\x81vila\xe2\x80\x8e, Castile and Le\xc3\xb3n, Spain'
 'Vivo entre Madrid y Mallorca.' 'Nuremberg, Bavaria, Germany'
 'Lausanne, Vaud, Switzerland' 'Reykjav\xc3\xadk, Capital Region, Iceland'
 'El Masnou, Catalonia, Spain' 'Barranquilla, Atlantico, Colombia' 'DK'
 'C\xc3\xa1diz, Andalusia, Spain' 'London, United Kingdom'
 'Pozuelo de Alarc\xc3\xb3n, Madrid, Spain' 'Galicia, Spain'
 'Alpedrete, Comunidad de Madrid, Spain'
 'Santiago, Santiago Metropolitan Region, Chile'
 'Newark, New Jersey, United States'
 'Alhaur\xc3\xadn de la Torre, Andalusia, Spain'
 'En Madrid, en el coraz\xc3\xb3n del barrio de Malasa\xc3\xb1a'
 'Burjassot, Valencian Community, Spain' 'Lisbon, Lisbon, Portugal'
 'George Town, George Town, Cayman Islands' 'Colombia'
 'Miles City, Montana, United States'
 'Zurich, Canton of Zurich, Switzerland' 'Florence, Tuscany, Italy'
 'Cambridge, England, United Kingdom' 'Norwalk, Connecticut, United States'
 'Hontanares de Eresma, Castilla y Le\xc3\xb3n, Spain' 'spain'
 'Boadilla del Monte, Comunidad de Madrid, Spain' 'SI'
 'Antwerp, Flanders, Belgium'
 'San Sebasti\xc3\xa1n de los Reyes, Community of Madrid, Spain'
 'Oviedo, Asturias, Spain' 'Dublin, Dublin, Ireland' 'Between Spain & USA'
 'ESPA\xc3\x91A'
 'Plaza de Espa\xc3\xb1a number 7. 9th floor, door J - 35007 - Las Palmas de Gran Canaria - Canary Islands'
 'El Berrueco, Comunidad de Madrid, Spain'
 'Chapiner\xc3\xada, Comunidad de Madrid, Spain'
 'Mexico City, Mexico City, Mexico'
 'Rio de Janeiro, State of Rio de Janeiro, Brazil'
 'Sant Josep de sa Talaia, Balearic Islands, Spain'
 'Puntagorda, Canarias, Spain' 'London, Reino Unido'
 'El Molar, Comunidad de Madrid, Spain'
 'Parque Coimbra, Comunidad de Madrid, Spain'
 'Magdalena Del Mar, Lima, Peru' 'Colombia, Huila, Colombia'
 'Los Angeles, California, United States' 'Marbella, Andalusia, Spain'
 'St. Joseph, Minnesota, United States' 'Madrid'
 'Miami, Florida, United States'
 'Cardenal Mendoza 28, 3A, Madrid. cp. 28011' 'Calafell, Catalonia, Spain'
 'Venezuela' 'Huy, Walloon Region, Belgium'
 'Villaviciosa de Od\xc3\xb3n, Community of Madrid, Spain'
 'Sanya, Hainan, China' 'Stavanger, Norway' 'VE'
 'Aunay-sous-Auneau, Centre-Val de Loire, France'
 'Guillermo Rolland, 5-4\xc2\xba Ext.Iz.' 'Rouen, Upper Normandy, France'
 'Santander, Cantabria, Spain' 'ES '
 'San Sebasti\xc3\xa1n de los Reyes, Comunidad de Madrid, Spain'
 'Las Palmas de Gran Canaria, Canarias, Spain'
 'Nairobi, Nairobi County, Kenya' 'london ' 'Utrecht, Utrecht, Netherlands'
 'Fuenlabrada, Comunidad de Madrid, Spain'
 'La Tablada, Buenos Aires Province, Argentina'
 'Valladolid, Castilla y Le\xc3\xb3n, Spain' 'Mexico'
 'Houston, Texas, United States'
 'Villaviciosa de Od\xc3\xb3n, Comunidad de Madrid, Spain'
 'Prague, Prague, Czech Republic'
 'Molina de Segura, Regi\xc3\xb3n de Murcia, Spain' 'Irlanda'
 'Jerez, Andalusia, Spain' 'Pattaya, Chon Buri, Thailand'
 'Evora, \xc3\x89vora District, Portugal' 'Cagliari, Sardegna, Italy'
 'Panama, Panama, Panama' 'Vilamarxant, Valencian Community, Spain'
 'Switzerland' 'espa\xc3\xb1a' 'Avenida Ciudad de Barcelona, 19, 6to Izq'
 'Torino, Piedmont, Italy' 'Sliema, Malta'
 'Geneva, Canton of Geneva, Switzerland' 'UK' 'M\xc3\xa9xico, DF'
 'Quito, Pichincha, Ecuador'
 'I was born and have always lived in this wonderful city'
 'El Prat de Llobregat, Catalonia, Spain' '-'
 'S\xc3\xa3o Paulo, S\xc3\xa3o Paulo, Brazil' 'Victoria, Australia'
 'Cordova, Andaluc\xc3\xada, Spain' 'Varese, Lombardia, Italy'
 'Rivas-Vaciamadrid, Comunidad de Madrid, Spain'
 'Boadilla del Monte, Community of Madrid, Spain' 'C/ Magdalena 11, 3 iz'
 'Auderghem, Brussels, Belgium' 'Algete, Community of Madrid, Spain'
 'Lyon, Rhone-Alpes, France' 'Pozuelo, Comunidad de Madrid, Spain'
 'Amsterdam, North Holland, The Netherlands'
 'Cluj-Napoca, Cluj County, Romania' 'Vigo, Galicia, Spain'
 'Florida, United States' 'Singapore' 'Madrid, SP, Spain'
 'Riga, Riga, Latvia' 'Pinto, Comunidad de Madrid, Spain'
 'Miami Beach, Florida, United States' 'Pamplona, Navarre, Spain'
 'Santa Eul\xc3\xa0ria des Riu, Balearic Islands, Spain'
 'Fuerteventura, Canarias, Spain' 'Santa Monica, California, United States'
 'Villanueva de Perales, Community of Madrid, Spain'
 'Santa Cruz de la Sierra, Santa Cruz Department, Bolivia'
 'Santa Cruz de Tenerife, Canarias, Spain'
 'Tracy, California, United States' 'Alfaro, La Rioja, Spain'
 'Cartagena, Region of Murcia, Spain'
 'Sucy-en-Brie, \xc3\x8ele-de-France, France'
 'Mexico City, Federal District, Mexico' 'GB'
 'San Sebastian, Basque Country, Spain' ' Spain,  Espa\xc3\xb1a,'
 'Lugo, Galicia, Spain' 'Toledo, Castile-La Mancha, Spain'
 'Cotia, S\xc3\xa3o Paulo, Brazil' 'Stockholm, Stockholm County, Sweden'
 'Newport News, Virginia, United States' 'Saumur, Pays de la Loire, France'
 'Torrelodones, Community of Madrid, Spain'
 'Santa Coloma de Gramenet, Catalunya, Spain'
 'Rosh Ha`Ayin, Hamerkaz, Israel' 'Nairobi, Nairobi, Kenya'
 'Valdemorillo, Comunidad de Madrid, Spain' 'Cuba' 'MX'
 'Sandbach, England, United Kingdom' 'Chiva, Valencian Community, Spain'
 'Joaqu\xc3\xadn Mar\xc3\xada L\xc3\xb3pez 11 S\xc3\xb3tano B'
 'Haro, La Rioja, Spain'
 'Caluire-et-Cuire, Auvergne-Rh\xc3\xb4ne-Alpes, France'
 'Aranjuez, Comunidad de Madrid, Spain' 'Barquisimeto, Lara, Venezuela'
 'Bremen, Bremen, Germany' 'C/Monederos 5 BajoB'
 'Villanueva de la Ca\xc3\xb1ada, Community of Madrid, Spain'
 'Key Biscayne, Florida, United States' 'Hamburg, Hamburg, Germany'
 'Kitzbuhel, Tyrol, Austria' 'Oleiros, Galicia, Spain'
 'Mambajao, Northern Mindanao, Philippines' 'Istanbul, TR'
 'El Puerto de Santa Mar\xc3\xada, Andalusia, Spain' 'Mallorca'
 'Sutton Coldfield, England, United Kingdom'
 'Naples, Florida, United States' 'Zurich, Zurich, Switzerland'
 'Cartagena, Regi\xc3\xb3n de Murcia, Spain' 'Germany'
 'San Diego, California, United States' 'Rafael Boti, 8 2\xc2\xbaA'
 'Aloc\xc3\xa9n, Castilla-La Mancha, Spain' 'DE'
 'Orlando, Florida, United States' 'La Orotava, Canarias, Spain' 'BE'
 'Netherlands' 'calle nanclares de oca, 1 Portal d bajo d cp 28022'
 'Curitiba, State of Paran\xc3\xa1, Brazil'
 'Saillagouse, Languedoc-Roussillon-Midi-Pyr\xc3\xa9n\xc3\xa9es, France'
 'Calle Gomes de Mora n6 4planta derecha.' 'Milan, Lombardy, Italy'
 'Boadilla del Monte' 'Puerto La Cruz, Anzoategui, Venezuela' 'TW'
 'Onil, Comunidad Valenciana, Spain' 'AS'
 'Fuenlabrada, Community of Madrid, Spain'
 'Lima District, Lima Region, Peru' 'Croydon, London'
 'Cabanillas del Campo, Castilla-La Mancha, Spain'
 'Nancy, Lorraine, France' 'Buenos Aires, Capital Federal, Argentina'
 'Las Rozas, Madrid, Spain' 'Moscow, Moscow, Russia'
 'Vilarmaior, Galicia, Spain' 'Milan, Lombardia, Italy'
 'Schaerbeek, Brussels, Belgium' 'Monterfil, Brittany, France' 'France '
 'Alcoi, Valencian Community, Spain' 'Boston, Massachusetts, United States'
 'Santiago Metropolitan Region, Chile' 'Galdakao, Euskadi, Spain' 'RU'
 'Washington, District of Columbia, United States' 'Catania, Sicily, Italy'
 'Dakar, Dakar, Senegal' 'Ostiz, Navarra, Spain'
 'La Albuera, Extremadura, Spain' 'Huesca, Aragon, Spain'
 'Badajoz, Extremadura, Spain' 'calle quintana n2 10pta6'
 'Oslo, Oslo, Kingdom of Norway'
 'Fuencarral-El Pardo 10 minutes away from las Cuatro Torres'
 'Prague, Hlavn\xc3\xad m\xc4\x9bsto Praha, Czech Republic'
 'Dallas, North Carolina, United States'
 'Fuencarral-El Pardo, Community of Madrid, Spain'
 'Vancouver, British Columbia, Canada'
 'C\xc3\xa1ceres\xe2\x80\x8e, Extremadura, Spain'
 'Murcia, Regi\xc3\xb3n de Murcia, Spain' 'Buenos Aires, Argentina'
 'Miami Shores, Florida, United States' 'Oslo, Oslo, Norway'
 'Miraflores de la Sierra, Community of Madrid, Spain'
 'Le\xc3\xb3n, Castile and Le\xc3\xb3n, Spain'
 'Philadelphia, Pennsylvania, United States'
 'San Nicandro Garganico, Puglia, Italy'
 'Metz, Alsace-Champagne-Ardenne-Lorraine, France' 'Costa Rica'
 'Vorarlberg, Austria' 'Madrid & Lake Tahoe'
 'Gainesville, Florida, United States' 'Ireland' 'Montreal, Quebec, Canada'
 'Mart\xc3\xadnez, Buenos Aires Province, Argentina'

In [25]:
state = ['Community of Madrid', '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c\xe8\x87\xaa\xe6\xb2\xbb\xe5\x8c\xba',
         'Regi\xc3\xa3o Aut\xc3\xb4noma de Madrid', 'madrid', '\xe9\xa9\xac\xe5\xbe\xb7\xe9\x87\x8c',
         '\xe9\xa6\xac\xe5\xbe\xb7\xe9\x87\x8c\xe8\x87\xaa\xe6\xb2\xbb\xe5\x8d\x80',
         'Espa\xc3\xb1a', '\xe8\xa5\xbf\xe7\x8f\xad\xe7\x89\x99',
         'Espa\xc3\xb1a,Madrid', 'MADRID', 'Espa\xc5\x84a',
         'Madrid capital', 'Spain', 'Communaut\xc3\xa9 de Madrid',
         'Madrid \nMadrid', 'Madrid Espa\xc3\xb1a', 'Madrid, Spain',
         'Autonome Gemeinschaft Madrid', 'Usera', ' ', '  ', '28','Comunidad de Madrid','']

for i in range(0, len(state)-1):
    listing.loc[(listing.state == state[i]), ['state']] = 'Madrid'

In [26]:
listing.state.unique()

array(['Madrid', nan, 'Salerno Fisciano', 'Valencian Community',
       'Alicante', 'La Habana', 'Barcelona'], dtype=object)

In [27]:
listing.state.value_counts()

Madrid                 13287
Salerno Fisciano           1
Barcelona                  1
La Habana                  1
Alicante                   1
Valencian Community        1
Name: state, dtype: int64

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">En las celdas anteriores verificamos que hay que hacer una labor de limpieza con los datos de las variables que se relacionan con la ciudad de Madrid y deshacernos de los registros que no pertenecen a la capital.<br><br></span></div>

In [28]:
listing = listing[listing.state == 'Madrid']
listing = listing[listing.country == 'Spain']
listing.shape

(13287, 63)

In [29]:
#Limpieza de neighbourhood_group_cleansed
listing.loc[(listing['neighbourhood_group_cleansed'] == 'Tetu\xc3\xa1n'), ['neighbourhood_group_cleansed']] = 'Tetuan'
listing.loc[(listing['neighbourhood_group_cleansed'] == 'Chamart\xc3\xadn'), ['neighbourhood_group_cleansed']] = 'Chamartin'
listing.loc[(listing['neighbourhood_group_cleansed'] == 'Chamber\xc3\xad'), ['neighbourhood_group_cleansed']] = 'Chamberi'
listing.loc[(listing['neighbourhood_group_cleansed'] == 'Vic\xc3\xa1lvaro'), ['neighbourhood_group_cleansed']] = 'Vicalvario'

In [30]:
listing.neighbourhood_group_cleansed.value_counts()

Centro                   6754
Chamberi                  958
Salamanca                 882
Arganzuela                788
Tetuan                    463
Moncloa - Aravaca         445
Retiro                    438
Latina                    379
Chamartin                 360
Carabanchel               357
Ciudad Lineal             309
Puente de Vallecas        222
Hortaleza                 185
Fuencarral - El Pardo     169
Usera                     144
San Blas - Canillejas     117
Villaverde                 83
Barajas                    80
Moratalaz                  74
Villa de Vallecas          46
Vicalvario                 34
Name: neighbourhood_group_cleansed, dtype: int64

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Nos vamos dando cuenta de los barrios con más opciones de alquiler en AirBnB.<br><br></span></div>

In [31]:
col_to_delete = ['host_location', 'neighbourhood', 'country','street', 'smart_location','market', 'city', 'state', 'neighbourhood_cleansed']

In [32]:
for i in range(0,len(col_to_delete)):
    listing.drop(col_to_delete[i], axis=1, inplace=True)

listing.shape

(13287, 54)

In [33]:
listing.isnull().sum(axis=0)

id                                     0
name                                   0
host_id                                0
host_name                              3
host_since                             3
host_is_superhost                      3
host_listings_count                    3
host_total_listings_count              3
host_verifications                     0
host_has_profile_pic                   3
host_identity_verified                 3
neighbourhood_group_cleansed           0
zipcode                              439
latitude                               0
longitude                              0
property_type                          0
room_type                              0
accommodates                           0
bathrooms                             49
bedrooms                              23
beds                                  49
bed_type                               0
amenities                              0
price                                  0
weekly_price                        9789
monthly_price                       9975
security_deposit                    7581
cleaning_fee                        5464
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
calendar_updated                       0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
number_of_reviews                      0
first_review                        2781
last_review                         2782
review_scores_rating                2906
review_scores_accuracy              2924
review_scores_cleanliness           2918
review_scores_checkin               2934
review_scores_communication         2918
review_scores_location              2936
review_scores_value                 2936
requires_license                       0
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                   2781
dtype: int64

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">¿Existen outliers en mi dataset? ¿Qué precio y características tienen los pisos más costosos de mi conjunto de datos?</span>
</div>
<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Sería interesante conocer qué precios tienen los pisos más costosos de mi dataset y qué carácteristicas tienen.<br><br></span>
</div>

In [34]:
outliers = listing[listing['price'] >= 1000]
outliers['price'].value_counts()

1000.0    3
3000.0    2
3189.0    1
7700.0    1
1890.0    1
1200.0    1
Name: price, dtype: int64

In [35]:
outliers.sort_values('price')

,id,name,host_id,host_name,host_since,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_group_cleansed,zipcode,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
10667,16199273,"Private Room in Rios Rosas, Madrid",102392514,Hemant,2016-11-03,f,1.0,1.0,"['email', 'phone']",t,f,Chamberi,28003,40.441251,-3.697699,Apartment,Private room,1,1.0,1.0,1.0,Real Bed,"{TV,""Wireless Internet"",Kitchen,Heating,""Famil...",1000.0,NaN,NaN,$100.00,15.0,1,5.0,1,15,4 months ago,29,59,89,364,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,f,moderate,f,f,1,NaN
5814,10715621,Lujoso apartamento en Gran Vìa 48,3256859,Fer & Fran,2012-08-14,f,14.0,14.0,"['email', 'phone', 'reviews', 'jumio']",t,t,Centro,28013,40.421617,-3.705310,Apartment,Entire home/apt,4,1.0,1.0,1.0,Real Bed,"{TV,""Wireless Internet"",""Air conditioning"",""Wh...",1000.0,NaN,NaN,NaN,NaN,2,15.0,2,1125,yesterday,6,34,64,160,4,2016-02-24,2016-08-03,80.0,9.0,9.0,7.0,6.0,8.0,9.0,t,t,strict,f,f,8,0.29
957,10495669,Ático centrico y tranquilo / Atic,46129526,Elisa,2015-10-09,f,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,Centro,28013,40.421374,-3.710629,Apartment,Entire home/apt,4,1.0,1.0,2.0,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",1000.0,NaN,NaN,NaN,20.0,2,5.0,1,1125,7 months ago,29,49,79,354,42,2016-01-14,2016-09-13,91.0,10.0,9.0,9.0,9.0,10.0,9.0,t,t,flexible,f,f,1,2.79
2246,14574259,"LONGTERM welcome-New,Central,100m² for 1-6 Per...",90311483,Tobias,2016-08-16,f,1.0,1.0,"['email', 'phone', 'reviews']",t,f,Centro,28005,40.409006,-3.710069,Apartment,Entire home/apt,6,2.0,2.0,2.0,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",1200.0,NaN,NaN,$500.00,50.0,1,0.0,3,1125,2 months ago,0,0,0,189,2,2016-08-27,2017-01-03,100.0,10.0,9.0,10.0,10.0,10.0,10.0,t,f,flexible,f,f,1,0.27
8855,6681279,Fantastico Piso Barrio de Salamanca,34972297,Juan Andres,2015-06-04,f,1.0,1.0,"['email', 'phone']",t,f,Salamanca,28006,40.434467,-3.682262,Condominium,Entire home/apt,4,2.0,2.0,2.0,Real Bed,"{TV,""Air conditioning"",Kitchen,Doorman,""Elevat...",1890.0,1843.0,1843.0,NaN,NaN,1,0.0,1,1125,8 months ago,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,f,strict,f,f,1,NaN
7993,361488,RETIRO PARK2 CHALET INDUSTRIAL-CHIC,1732442,Anouk,2012-02-10,f,12.0,12.0,"['email', 'phone', 'reviews', 'jumio']",t,t,Retiro,28007,40.409084,-3.673131,Chalet,Entire home/apt,6,3.0,3.0,3.0,Real Bed,"{""Wireless Internet"",Kitchen,""Free parking on ...",3000.0,910.0,2910.0,"$3,000.00",100.0,1,250.0,5,365,2 months ago,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,f,strict,f,f,12,NaN
8002,1727101,RETIRO PARK1 CHALET INDUSTRIAL-CHIC,1732442,Anouk,2012-02-10,f,12.0,12.0,"['email', 'phone', 'reviews', 'jumio']",t,t,Retiro,28007,40.410194,-3.671795,House,Entire home/apt,6,3.0,3.0,3.0,Real Bed,"{""Wireless Internet"",Kitchen,""Free parking on ...",3000.0,910.0,2910.0,"$3,000.00",100.0,1,250.0,5,1125,2 months ago,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,f,flexible,f,f,12,NaN
8027,2744574,Mansion with royal garden,9631554,K&S,2013-10-25,t,1.0,1.0,"['email', 'phone', 'reviews', 'jumio']",t,t,Salamanca,-,40.423505,-3.689261,House,Entire home/apt,10,6.0,4.0,9.0,Real Bed,{},3189.0,NaN,NaN,NaN,NaN,1,0.0,1,1125,5 weeks ago,30,60,90,365,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,f,flexible,f,f,1,NaN
10828,1250842,Habitación Moncloa-AravacaArgüelles,6815584,Héctor,2013-06-09,f,1.0,1.0,[],t,f,Moncloa - Aravaca,28008,40.430939,-3.721799,Apartment,Private room,5,NaN,1.0,NaN,Real Bed,{},7700.0,NaN,NaN,NaN,NaN,1,0.0,1,1125,7 months ago,29,59,89,364,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,t,flexible,f,f,1,NaN

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Podemos sacar varias conclusiones:<br> <br>
    - 1) Existe un alquiler de 7700 Euros por noche, por una habitación! A menos que sea una habitación del Palacio Real, no lo creo muy real. Eliminamos este regitro (id=1250842)<br>
    - 2) Existe otro registro, que es una habitación de alquiler por 1000 euros la noche. Parece no tener mucho sentido. (id=16199273)<br>
    - 3) Existen pisos que en el campo 'number_of_reviews' tienen cero comentarios. Esto indica que nunca han sido alquilados. Tomando en consideración el precio, pueden ser considerados como outliers. Eliminar.<br></span>
</div>

In [36]:
id_to_delete = [6681279, 361488, 1727101, 2744574, 1250842, 16199273]
for i in range(0,len(id_to_delete)):
    listing = listing[listing['id'] != id_to_delete[i] ]

In [37]:
#outliers.dropna(subset=['reviews_per_month'])

<br><br><div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Tenemos otra serie de datos (que aún no sé si utilizaré pero pueden servirme a futuro) que deben ser cambiados a su formato correcto. Es el caso de variables con fechas y variables booleanas, que se tratan a continuación:</span>
</div>

In [38]:
# Cambiamos el formato a booleano
bools = ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 'requires_license', 'instant_bookable', 
         'require_guest_profile_picture', 'require_guest_phone_verification']
for i in bools:
    listing[i] = listing[i].map({'t': True, 'f': False})

In [39]:
# Cambiamos el formato de las fechas
fechas = ['host_since', 'first_review', 'last_review']
for i in fechas:
    listing[i] = pd.to_datetime(listing[i], infer_datetime_format=True)

In [40]:
listing.head(3)

,id,name,host_id,host_name,host_since,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_group_cleansed,zipcode,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
9135,1690312,Apartamento 200m2 para 5/6 personas,8815003,Maite,2013-09-13,False,2.0,2.0,"['email', 'phone', 'reviews', 'jumio']",True,True,Chamartin,28016,40.456181,-3.676956,Apartment,Entire home/apt,6,2.0,3.0,3.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",200.0,NaN,NaN,$500.00,NaN,1,50.0,2,7,2 weeks ago,30,60,90,365,1,2015-05-24,2015-05-24,80.0,8.0,10.0,10.0,8.0,10.0,8.0,True,False,flexible,False,False,2,0.04
441,4678105,Central sunny apartment with views,17705919,Barbara Y Javi,2014-07-06,False,1.0,1.0,"['email', 'phone', 'reviews', 'jumio']",True,True,Centro,28005,40.412441,-3.711110,Apartment,Entire home/apt,2,1.0,2.0,2.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Elev...",100.0,NaN,NaN,$150.00,10.0,1,0.0,2,1125,2 weeks ago,0,6,36,311,20,2015-02-01,2016-10-04,94.0,9.0,9.0,10.0,10.0,10.0,9.0,True,False,flexible,False,False,1,0.75
5021,13091807,long rental study old town madrid 2,21137168,Ale,2014-09-09,False,4.0,4.0,"['email', 'phone', 'reviews']",True,False,Centro,28004,40.426694,-3.707727,Apartment,Private room,2,1.0,2.0,1.0,Real Bed,"{Internet,""Wireless Internet"",""Air conditionin...",39.0,NaN,NaN,NaN,NaN,1,0.0,7,365,today,7,9,29,281,2,2017-03-07,2017-03-20,80.0,10.0,9.0,10.0,9.0,10.0,10.0,True,True,strict,False,False,4,1.82

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">Generamos el nuevo fichero con la data limpia</span>
</div>

In [41]:
listing.to_csv('./listing_clean.csv', sep=',')

<div style="text-align: left;"><br><br><br>
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">De momento hemos limpiado los datos del dataset Listing...<br><br>Seguimos...<br><br></span>
</div>

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">Dataset "Calendar":</span>
</div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
Vamos ahora a trabajar con el dataset Calendar. Este dataset es importante para conocer por ejemplo, la disponibilidad de pisos durante un año, entre otras cosas interesantes.</span>
</div>

In [42]:
calendar.head()

   listing_id        date available   price
0     7830063  2018-01-03         t  $42.00
1     7830063  2018-01-02         t  $42.00
2     7830063  2018-01-01         t  $42.00
3     7830063  2017-12-31         f     NaN
4     7830063  2017-12-30         f     NaN

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
Revisamos los data types de las columnas para saber si son del tipo correcto</span>
</div>

In [43]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4867275 entries, 0 to 4867274
Data columns (total 4 columns):
listing_id    int64
date          object
available     object
price         object
dtypes: int64(1), object(3)
memory usage: 148.5+ MB

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
EL dataset calendar contiene data de los precios para cada piso en alquiler para todo un año y con información de la disponibilidad de los mismos.
<br><br>
Al igual que el dataset anterior, revisamos que los tipos de datos sean los correctos y, si no lo son, convertirlos. 
<br><br>
Nos damos cuenta de que la columna "date", "available" y "price" no tienen el formato que deberían. 
Date debe ser convertido al formato datetime, "price" al igual que el dataset anterior debe cambiarse a float, eliminando previamente el símbolo de dólar y eliminando el punto de separador de miles; y finalmente "available" debe ser una variable boolean.
</span>
</div>

In [44]:
# Cambiamos el formato de las fechas
calendar['date'] = pd.to_datetime(calendar.date, infer_datetime_format=True)
calendar['date'].head(3)

0   2018-01-03
1   2018-01-02
2   2018-01-01
Name: date, dtype: datetime64[ns]

In [45]:
# Quitamos el signo de dólar y cualquier separador de miles donde el precio no sea NA
calendar['price'] = calendar.loc[calendar.price.notnull()].price.apply(lambda x: re.sub('[$,]', '', x))

In [46]:
# Price se cambia a numérico
calendar['price'] = pd.to_numeric(calendar.price)
calendar['price'].head(3)

0    42.0
1    42.0
2    42.0
Name: price, dtype: float64

In [47]:
# La columna 'available' se convierte en boolean
calendar['available'] = calendar['available'].map({'t': True, 'f': False})
calendar['available'].head(3)

0    True
1    True
2    True
Name: available, dtype: bool

In [48]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4867275 entries, 0 to 4867274
Data columns (total 4 columns):
listing_id    int64
date          datetime64[ns]
available     bool
price         float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 116.0 MB

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
Hacemos un chequeo típico de la data para verificar anormalidades o cualquier cosa que nos parezca extraña.
<br><br>
Vamos a generar una pequeña tabla con los valores mínimos y máximos y los missing values para la columna "date" y "price"
</span>
</div>

In [49]:
# Get min, max and number of missing values for Date and Price
min_date = calendar.date.min()
max_date = calendar.date.max()
num_list = len(calendar.listing_id.unique())
price_missing = len(calendar.loc[pd.isnull(calendar.price)])
date_missing = len(calendar.loc[pd.isnull(calendar.date)])
min_price = calendar.price.min()
max_price = calendar.price.max()

lista = [['Precio', min_price, max_price, price_missing], ['Fecha', min_date, max_date, date_missing]]
cols = ['Column','Min','Max','Missing']

data = pd.DataFrame(lista, columns=cols)
data

   Column                  Min                  Max  Missing
0  Precio                    9                15505  2121828
1   Fecha  2017-04-07 00:00:00  2018-04-07 00:00:00        0

In [50]:
len(calendar)

4867275

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
El precio parece ser muy diferente entre los apartamentos, desde 9.00 dólares por noche a 15.505.00 por noche. Recordemos que no hemos separado los pisos entre los 3 tipos de habitaciones diponibles (habitación completa, habitación compartida y piso completo) lo que podría explicar el por qué estos valores máximos y mínimos.<br><br>
Vemos también que el dataset tiene datos de un año, desde la fecha que se extrajo la data hasta un año siguiente. Nos está mostrando el calendario de reservas para un año desde el 04/07/2017.
<br><br>
Es de notar la cifra en la tabla en cuanto a datos missing de precio. Son 2121828 datos missing, que forman casi el 50% de los datos calendario completo. 
<br><br>
Los datos faltantes en este dataset, representan cuando se ha reservado un piso. 
Que un dato NA sea considerado como un piso reservado tiene lógica ya que es probable que el dato no haya podido ser extraído al momento de hacer scrapping, ya que estaba reservado. <br><br>
Convertimos este nuevo dataset limpio, a un fichero .csv
</span>
</div>

In [51]:
calendar.to_csv('./calendar_clean.csv', sep=',')

<br><div style="text-align: left;">
    <span style="font-weight: bold; color:#FF7674; font-family: 'Courier New'; font-size: 2em;">Dataset "Review":</span>
</div>

<div style="text-align: left;">
    <span style="color:#2467C0; font-family: 'Courier New'; font-size: 1.5em;">
Finalmente tenemos el dataset "Review" el cuál trabajaremos para tratar de sacar información de dicho DataSet.</span>
</div>

In [52]:
review.head(3)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,15128601,103956852,2016-09-25,48832799,Amparo,"Apartamento muy acogedor, limpio y cómodo, en ..."
1,15128601,105883025,2016-10-03,87158075,Daniela,"La descripción del anuncio era correcta, las f..."
2,15128601,106595943,2016-10-07,10102108,Fabien,Nice and cosy place. Really peaceful and quiet...

In [53]:
review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306870 entries, 0 to 306869
Data columns (total 6 columns):
listing_id       306870 non-null int64
id               306870 non-null int64
date             306870 non-null object
reviewer_id      306870 non-null int64
reviewer_name    306870 non-null object
comments         306641 non-null object
dtypes: int64(3), object(3)
memory usage: 14.0+ MB

In [54]:
# Cambiamos el formato de las fechas
review['date'] = pd.to_datetime(review.date, infer_datetime_format=True)
review['date'].head(3)

0   2016-09-25
1   2016-10-03
2   2016-10-07
Name: date, dtype: datetime64[ns]

In [55]:
review.to_csv('./review_clean.csv', sep=',')